###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Nikola Tesla",
    "age": 80,
    "email": "nikolatesla@gmail.com"
}

###

GET http://localhost:3000/api/users/655e40163842f53f23ac229a HTTP/1.1


###
DELETE http://localhost:3000/api/users/655e40163842f53f23ac229a HTTP/1.1

###
PUT http://localhost:3000/api/users/655e40163842f53f23ac229a HTTP/1.1
Content-Type: application/json

{
    "name": "Carlos Acosta",
    "age": 45,
    "email": "johnconway@email.com"
}